# Default configuration for SandCore Plugin
# Immerse yourself in the epic world of SandCore,
# where every interface is a gateway to ancient lore and hidden power.

# Leveling Configuration
leveling:
  xp_per_level: 100
  skill_points_per_level: 1

# Admin GUI Configuration
admin_gui:
  # The admin GUI now pulls settings from the global guis section below.
  title: '&#AA0000Admin Stats GUI - Command Over Destiny'

# Global GUI Settings for all interfaces
guis:
  default:
    # Default overall size for GUIs (allowable values: 9, 18, 27, 36, 45, 54)
    size: 27
    # Default background filler item used when not otherwise specified.
    background:
      material: BLACK_STAINED_GLASS_PANE
      display_name: ' '
      lore:
        - '&#111111A mysterious void from beyond.'
  class_selection:
    title: '&#FFD700Select Your Class'
    size: 27
    # Specify which slots will hold your class icons. (Middle row slots in a 27-slot GUI)
    icon_slots:
      - 10
      - 11
      - 12
      - 13
      - 14
    # Filler configuration for slots not used by class icons.
    filler:
      material: BLACK_STAINED_GLASS_PANE
      display_name: ' '
      lore:
        - '&#222222A mystical barrier of the ancient realm.'
  admin:
    title: '&#AA0000Admin Stats GUI - Command Over Destiny'
    size: 27
    # Arrange admin items in a centered row (you can later customize with additional lore)
    icon_slots:
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17

# User Interface Configuration (other UI elements)
ui:
  header: '&#00FF7FSANDCORE SKILLS'
  reload-message: '&#FFD700Config reloaded! &#32CD32(v%version%)'