classes:
  warrior:
    health: 30.0
    damage: 5.0
    speed: 0.1
    defense: 3.0
  mage:
    health: 20.0
    damage: 7.0
    speed: 0.1
    defense: 1.5
  archer:
    health: 25.0
    damage: 4.0
    speed: 0.12
    defense: 2.0