# Default configuration for SandCore Plugin
# Immerse yourself in the epic world of SandCore,
# where every interface is a gateway to ancient lore and hidden power.

# (Removed hologram & skill tree configuration)

# Admin GUI Configuration
admin_gui:
  # The admin GUI now pulls settings from the global guis section below.
  title: '&#AA0000Admin Stats GUI - Command Over Destiny'

# Global GUI Settings for all interfaces
guis:
  default:
    # Default overall size for GUIs (allowable values: 9, 18, 27, 36, 45, 54)
    size: 27
    # Default background filler item used when not otherwise specified.
    background:
      material: BLACK_STAINED_GLASS_PANE
      display_name: ' '
      lore:
        - '&#111111A mysterious void from beyond.'
  class_selection:
    title: '&#FFD700Select Your Class'
    size: 9
    # Specify which slots will hold your class icons.
    icon_slots:
      - 0
      - 2
      - 4
      - 6
      - 8
    # Filler configuration for slots not used by class icons.
    filler:
      material: BLACK_STAINED_GLASS_PANE
      display_name: ' '
      lore:
        - '&#222222A mystical barrier of the ancient realm.'
  admin:
    title: '&#AA0000Admin Stats GUI - Command Over Destiny'
    size: 9
    icon_slots:
      - 1
      - 3
      - 5
      - 7

# User Interface Configuration (other UI elements)
ui:
  header: '&#00FF7FSANDCORE SKILLS'
  reload-message: '&#FFD700Config reloaded! &#32CD32(v%version%)'