# Default configuration for SandCore Plugin
# Immerse yourself in the epic world of SandCore,
# where every interface is a gateway to ancient lore and hidden power.

# Leveling Configuration
leveling:
  combat:
    xp_per_level: 1000
  skills:
    lumber:
      xp_per_level: 500
    mining:
      xp_per_level: 500
    fishing:
      xp_per_level: 300
  skill_points_per_level: 1

# Admin GUI Configuration
admin_gui:
  title: '&#AA0000Admin Stats GUI - Command Over Destiny'

# Global GUI Settings for all interfaces
guis:
  default:
    size: 27
    background:
      material: BLACK_STAINED_GLASS_PANE
      display_name: ' '
      lore:
        - '&#111111A mysterious void from beyond.'
  class_selection:
    title: '&#FFD700Select Your Class'
    size: 27
    icon_slots:
      - 10
      - 11
      - 12
      - 13
      - 14
    filler:
      material: BLACK_STAINED_GLASS_PANE
      display_name: ' '
      lore:
        - '&#222222A mystical barrier of the ancient realm.'
  admin:
    title: '&#AA0000Admin Stats GUI - Command Over Destiny'
    size: 27
    icon_slots:
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17

# User Interface Configuration (other UI elements)
ui:
  header: '&#00FF7FSANDCORE SKILLS'
  reload-message: '&#FFD700Config reloaded! &#32CD32(v%version%)'