name: SandCore
main: com.sandcore.mmo.SandCore
version: 1.0
commands:
  class:
    description: "Manage class selection and info."
    usage: "/class <select|info|addcp>"
  stats:
    description: "Manage stat upgrades."
    usage: "/stats <upgrade|add>"
permissions:
  sandcore.admin:
    description: "Allows administrative commands for SandCore."
    default: op