name: SandCore
main: com.sandcore.SandCore
version: 1.2.0
api-version: 1.21
authors:
  - ManOfTheSand
description: "Immerse yourself in the epic world of SandCore, an MMO plugin brimming with vivid lore and dynamic adventures. Choose your class, hone your skills, and shape your destiny!"
depend: [DecentHolograms]

commands:
  class:
    description: "Manage your class selection and unlock hidden powers."
    usage: "/class <select|info|addcp>"
  stats:
    description: "Display and upgrade your character's combat stats."
    usage: "/stats <upgrade|add|view>"
  adminstats:
    description: "Admin command for viewing and modifying player stats."
    usage: "/adminstats <player>"
  screload:
    description: "Reload SandCore configuration and rejuvenate your adventure."
    usage: "/screload"
    aliases: [sreload]
  xp:
    description: "Add experience to your combat and gathering skills."
    usage: "/xp <combat|lumber|mining|fishing> <amount>"

permissions:
  sandcore.reload:
    description: "Allows reloading the SandCore configuration."
    default: op
  sandcore.admin:
    description: "Grants access to advanced admin commands."
    default: op