name: SandCore
main: com.sandcore.SandCore
version: 1.0
api-version: 1.21
commands:
  class:
    description: "Manage your class selection."
    usage: "/class <select|info|addcp>"
  stats:
    description: "Manage your stat upgrades."
    usage: "/stats <upgrade|add>"
  adminstats:
    description: "Admin command for player stats management."
    usage: "/adminstats <player>"
  skilltree:
    description: "Open the skill tree GUI."
    usage: "/skilltree"
permissions:
  sandcore.admin:
    description: "Allows access to admin commands."
    default: op
dependencies:
  server:
    DecentHolograms:
      load: BEFORE
      required: true # This is the default when not presentt